// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbEoLYKtDhjVI7lNSbsvskv2RnTnlP358',
    appId: '1:864754519111:web:53ca2c80412580ebd53562',
    messagingSenderId: '864754519111',
    projectId: 'time-tracking-805e5',
    authDomain: 'time-tracking-805e5.firebaseapp.com',
    storageBucket: 'time-tracking-805e5.appspot.com',
    measurementId: 'G-R48L0XCNES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHF6zIQELfJf12YHsjfFSh4TkR3sLy3uk',
    appId: '1:864754519111:android:100c9b2ba4898419d53562',
    messagingSenderId: '864754519111',
    projectId: 'time-tracking-805e5',
    storageBucket: 'time-tracking-805e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm9Aznx6kHHbeVIL4SuEShri7_knOQUzE',
    appId: '1:864754519111:ios:3df711c5cf9d06dad53562',
    messagingSenderId: '864754519111',
    projectId: 'time-tracking-805e5',
    storageBucket: 'time-tracking-805e5.appspot.com',
    iosClientId: '864754519111-gnetvv911g57bm1f6gb3mfuqv22l237a.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracking',
  );
}
